version: "3"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 6wyvbr64yb46r5bvyw4er65bywe46ry
      POSTGRES_PASSWORD: vw45y6vt4ty5fwe456ywer4v5ywe5
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/myapp
    ports:
      - 4000:4000